---
  - name: YUM | Install EPEL-RELEASE
    yum:
      name: epel-release
      state: latest
      update_cache: yes
    tags: 
      - nginx
      - nginx-install

  - name: YUM | install nginx
    yum:
      name: nginx
      state: latest
      update_cache: yes
    tags:
      - nginx
      - nginx-install
...