---
# tasks file for ansible/common
  - name: YUM | Ensure epel-release installed
    yum:
      name: epel-release
      state: present
    update_cache: yes
    tags:
      - python3
      - ansible
      - cockpit
      - docker
      - nginx
...