---
# defaults file for cockpit
cockpit_server_name: cockpit.example.com
cockpit_port: 8080
cockpit_allowed_network: "{{ ansible_default_ipv4.network|default('192.168.1.0') }}/{{ ('192.168.1.0/' ~ ansible_default_ipv4.netmask|default('255.255.255.0'))|ipaddr('prefix') }}"